//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentacion.base_de_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistema_pacientesEntities : DbContext
    {
        public sistema_pacientesEntities()
            : base("name=sistema_pacientesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ma_tipos_usuarios> ma_tipos_usuarios { get; set; }
        public virtual DbSet<ma_usuarios> ma_usuarios { get; set; }
        public virtual DbSet<ma_causas> ma_causas { get; set; }
        public virtual DbSet<ma_coberturas> ma_coberturas { get; set; }
        public virtual DbSet<ma_direccion_facturas> ma_direccion_facturas { get; set; }
        public virtual DbSet<ma_domicilios> ma_domicilios { get; set; }
        public virtual DbSet<ma_ingresos> ma_ingresos { get; set; }
        public virtual DbSet<ma_medicos> ma_medicos { get; set; }
        public virtual DbSet<ma_medicos_clinica> ma_medicos_clinica { get; set; }
        public virtual DbSet<ma_medicos_solicita_ingresos> ma_medicos_solicita_ingresos { get; set; }
        public virtual DbSet<ma_pacientes> ma_pacientes { get; set; }
        public virtual DbSet<ma_religiones> ma_religiones { get; set; }
        public virtual DbSet<ma_seguros> ma_seguros { get; set; }
        public virtual DbSet<ma_seguros_pacientes> ma_seguros_pacientes { get; set; }
        public virtual DbSet<ma_solicitudes_medicas> ma_solicitudes_medicas { get; set; }
        public virtual DbSet<ma_tipos_ingresos> ma_tipos_ingresos { get; set; }
        public virtual DbSet<ma_tipos_seguro> ma_tipos_seguro { get; set; }
        public virtual DbSet<ma_tipos_seguros_excluidos> ma_tipos_seguros_excluidos { get; set; }
        public virtual DbSet<ma_tratamientos> ma_tratamientos { get; set; }
        public virtual DbSet<ma_parientes_pacientes> ma_parientes_pacientes { get; set; }
        public virtual DbSet<ma_tipo_pariente> ma_tipo_pariente { get; set; }
        public virtual DbSet<ma_causas_pacientes1> ma_causas_pacientes1Set { get; set; }
        public virtual DbSet<ma_otros_domicilios> ma_otros_domicilios { get; set; }
        public virtual DbSet<ma_seguro_pacientes_excluidos> ma_seguro_pacientes_excluidos { get; set; }
    }
}
