//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentacion.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_otros_domicilios
    {
        public int id_domilicio { get; set; }
        public int id_paciente { get; set; }
        public string domiciliado { get; set; }
        public int id_otro_domicilio { get; set; }
    
        public virtual ma_domicilios ma_domicilios { get; set; }
        public virtual ma_pacientes ma_pacientes { get; set; }
    }
}
