//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentacion.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_parientes_pacientes
    {
        public int id_pariente { get; set; }
        public int id_paciente { get; set; }
        public int tipo_pariente { get; set; }
        public string relacion { get; set; }
        public string Nombre { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string calle { get; set; }
        public string localidad { get; set; }
        public string pais { get; set; }
    
        public virtual ma_pacientes ma_pacientes { get; set; }
        public virtual ma_tipo_pariente ma_tipo_pariente { get; set; }
    }
}
