//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentacion.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ma_pacientes()
        {
            this.ma_ingresos = new HashSet<ma_ingresos>();
            this.ma_solicitudes_medicas = new HashSet<ma_solicitudes_medicas>();
            this.ma_parientes_pacientes = new HashSet<ma_parientes_pacientes>();
            this.ma_causas_pacientes = new HashSet<ma_causas_pacientes1>();
            this.ma_otros_domicilios = new HashSet<ma_otros_domicilios>();
        }
    
        public int id_paciente { get; set; }
        public string num_seguridad_social { get; set; }
        public string num_tarjeta { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string apellido_solte { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string lugar_nacimiento { get; set; }
        public string profesion { get; set; }
        public string idioma { get; set; }
        public string nacionalidad { get; set; }
        public string permiso_residencia { get; set; }
        public string estado_civil { get; set; }
        public Nullable<int> id_religion { get; set; }
        public int id_domicilio { get; set; }
        public int id_tratamiento { get; set; }
        public int id_medico_clinica { get; set; }
        public Nullable<int> id_medicos_solicita { get; set; }
        public int id_seguro_pacientes { get; set; }
        public Nullable<int> id_direccion_fac { get; set; }
    
        public virtual ma_direccion_facturas ma_direccion_facturas { get; set; }
        public virtual ma_domicilios ma_domicilios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_ingresos> ma_ingresos { get; set; }
        public virtual ma_medicos_clinica ma_medicos_clinica { get; set; }
        public virtual ma_medicos_solicita_ingresos ma_medicos_solicita_ingresos { get; set; }
        public virtual ma_religiones ma_religiones { get; set; }
        public virtual ma_seguros_pacientes ma_seguros_pacientes { get; set; }
        public virtual ma_tratamientos ma_tratamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_solicitudes_medicas> ma_solicitudes_medicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_parientes_pacientes> ma_parientes_pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_causas_pacientes1> ma_causas_pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_otros_domicilios> ma_otros_domicilios { get; set; }
    }
}
