//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentacion.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seguros_pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ma_seguros_pacientes()
        {
            this.ma_pacientes = new HashSet<ma_pacientes>();
            this.ma_seguro_pacientes_excluidos = new HashSet<ma_seguro_pacientes_excluidos>();
        }
    
        public int id_seguro_paciente { get; set; }
        public int id_seguro { get; set; }
        public string num_poliza { get; set; }
        public int id_tipo_seguro { get; set; }
        public Nullable<int> id_cobertura { get; set; }
    
        public virtual ma_coberturas ma_coberturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_pacientes> ma_pacientes { get; set; }
        public virtual ma_seguros ma_seguros { get; set; }
        public virtual ma_tipos_seguro ma_tipos_seguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_seguro_pacientes_excluidos> ma_seguro_pacientes_excluidos { get; set; }
    }
}
