//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentacion.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seguro_pacientes_excluidos
    {
        public Nullable<int> id_seguro_paciente { get; set; }
        public Nullable<int> id_tipo_exclusion { get; set; }
        public string asegurador { get; set; }
        public string num_accidente { get; set; }
        public string num_empresa { get; set; }
        public string lugar_accidente { get; set; }
        public Nullable<System.DateTime> fecha_accidente { get; set; }
        public string num_disposicion_invalidez { get; set; }
        public int id_seguro_paciente_excluido { get; set; }
    
        public virtual ma_seguros_pacientes ma_seguros_pacientes { get; set; }
        public virtual ma_tipos_seguros_excluidos ma_tipos_seguros_excluidos { get; set; }
    }
}
