//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace presentacion.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_usuarios
    {
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public string pass { get; set; }
        public Nullable<int> id_tipo { get; set; }
    
        public virtual ma_tipos_usuarios ma_tipos_usuarios { get; set; }
    }
}
